[project]
name = "drweb-test-task"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.121.0",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
